using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using NAudio;
using NAudio.Wave;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Diagnostics;
using System.IO;

namespace play_audio
{
    /// <summary>
    /// Interaction logic for MainWindow.xaml
    /// </summary>
    public partial class MainWindow : Window
    {
       // public ChartValues<Polyline> PolylineCollection;
        public MainWindow()
        {
            InitializeComponent();

           // StartRecording(5);
            playaudio.IsEnabled = true;
        }
        
        WaveFileReader wfr;
        Polyline pl;


        double canH = 0;
        double canW = 0;
        double plH = 0;
        double plW = 0;
        int time = 0;
        double seconds = 0;
        int numtodisplay = 2205; //No of samples displayed in a second

        public float[] getCoefficients()
        {
            string[] lines = System.IO.File.ReadAllLines(@"D:\GIT\aerowinrt\audio_use\coefficients.txt");


            string[] coefficients = new string[10];
            float[] coefficients1 = new float[10];
            foreach (string line in lines)
            {
                coefficients = line.Split(new char[] { ',' });

            }

            for (int i = 0; i < coefficients.Length; i++)
            {
                coefficients1[i] = float.Parse(coefficients[i]);
            }

            return (coefficients1);
        }


        

        private void playaudio_Click(object sender, RoutedEventArgs e)
        {
            float[] coefficients = new float[10];
            float[] a = new float[5];
            float[] b = new float[5];
            Queue<float> displaysht = new Queue<float>();

            canH = waveCanvas.Height;
            canW = waveCanvas.Width;

            pl = new Polyline();
            pl.Stroke = Brushes.Black;
            pl.Name = "waveform";
            pl.StrokeThickness = 1;
            pl.MaxHeight = canH - 4;
            pl.MaxWidth = canW - 4;
            plH = pl.MaxHeight;
            plW = pl.MaxWidth;
            

            wfr = new WaveFileReader(@"D:\GIT\aerowinrt\audio_use\record4.wav");
            for (int i = 0; i < wfr.SampleCount; i++)
            {
                if (i % 100 == 0)
                {
                    displaysht.Enqueue(wfr.ReadNextSampleFrame()[0]);
                }
                else
                {
                    var dummy = wfr.ReadNextSampleFrame()[0];
                }
            }

            Debug.Print($"Max: {displaysht.Max()}");

            //byte[] allBytes = File.ReadAllBytes(@"D:\GIT\aerowinrt\audio_use\record4.wav");
            //Debug.Print("allBytes length : " + allBytes.Length);

            double secondsRecorded = (double)(1.0 * wfr.Length / wfr.WaveFormat.AverageBytesPerSecond * 1.0);
            

            byte[] shts = new byte[4];

            /*
            for (int i = 0; i < allBytes.Length-1 ; i += 100)
            {
                shts[3] = allBytes[i];
                shts[2] = allBytes[i + 1];
                shts[1] = allBytes[i + 2];
                shts[0] = allBytes[i + 3];

                displaysht.Enqueue(BitConverter.ToInt32(shts, 0));
                
            }
            */

            this.waveCanvas.Children.Clear();
            pl.Points.Clear();
            float[] shts2 = displaysht.ToArray();
            float[] shts3 = displaysht.ToArray();

            coefficients = getCoefficients();
            for (int i = 0; i < 5; i++)
            {
                a[i] = coefficients[i];

            }
            for (int i = 5; i < coefficients.Length; i++)
            {
                b[i - 5] = coefficients[i];

            }

            for (Int32 x = 4; x < shts2.Length; x++)
            {
                //coefficients from file generated by MATLAB
                shts3[x] = ((b[0] * x) + (b[1] * (x - 1)) + (b[2] * (x - 2)) + (b[3] * (x - 3)) + (b[4] * (x - 4)) + (a[1] * shts2[x - 1]) + (a[2] * shts2[x - 2]) + (a[3] * shts2[x - 3]) + (a[4] * shts2[x - 4]));

            }




            for (Int32 x = 0; x < shts3.Length; ++x)
            {
                //pl.Points.Add(new Point(x, shts3[x] / 0.01514753));
                Point p = new Point { X = 1.99 * x * plW / 1800 , Y = plH / 2.0 - shts3[x]*plH*10 };
                pl.Points.Add(p);
                //pl.Points.Add(Normalize(x, shts3[x]));
                //Point p1 = new Point();
                //p1.X = x;
                //p1.Y = shts3[x];
                //pl.Points.Add(p1);


            }

            this.waveCanvas.Children.Add(pl);
        }

        Point Normalize(Int32 x, float y)
        {
            Point p = new Point
            {

                X = 1.99 * x / 1800 * plW,
                Y = plH / 2.0 - y / (Math.Pow(2, -1) * 1.0) * (plH)
            };
            //Debug.Print("Points added: " + p);
            double k = p.Y;
            double h = p.X;
            //File.AppendAllText(@"D:\GIT\aerowinrt\audio_use\textfile2.txt", "(" + h.ToString("#.###") + "," + k.ToString(" #.##### ") + "),");
            return p;
        }

        //private void playaudio_Click(object sender, RoutedEventArgs e)
        //{
        //    playaudio.IsEnabled = false;
        //    waveCanvas.Children.Clear();
                        

        //}
    }
}
